#!/bin/bash

#PBS -l select=1:ngpus=4
#PBS -l walltime=30:00:00
#PBS -j oe
#PBS -P personal-xxxxxxxx
#PBS -q normal
#PBS -N gpuJob

cd $PBS_O_WORKDIR || exit $?
[ -d log ] || mkdir log

mkdir /tmp/.cache

module load miniforge3
conda activate bimjepa

{
    # Check that the correct Conda environment is active
    echo "Active Conda Environment:"
    conda info --envs

    cd ../.. || exit 1
    python -m bimjepa fit -c configs/BIM-JEPA/pretraining/combined_pretrain_original.yaml

} > out.$PBS_JOBID 2> err.$PBS_JOBID