#!/bin/bash

#PBS -l select=1:ngpus=1
#PBS -l walltime=1:00:00
#PBS -j oe
#PBS -P personal-xxxxxxxx
#PBS -q normal
#PBS -N gpuJob

cd $PBS_O_WORKDIR || exit $?
[ -d log ] || mkdir log

mkdir /tmp/.cache

module load miniforge3
conda activate bimjepa

{
    # Check that the correct Conda environment is active
    echo "Active Conda Environment:"
    conda info --envs
    # Final test run on BIMGEOM. Run only once, after all tuning is complete.
    cd ../.. || exit 1
    python -m bimjepa.tasks.classification test \
        -c configs/BIM-JEPA/classification/bimgeom_classification.yaml \
        --ckpt_path /home/users/nus/xxxxxxxx/jepa/artifacts/lightning_logs/version_312/checkpoints/epoch=349-step=88550.ckpt

} > out.$PBS_JOBID 2> err.$PBS_JOBID